import { BrainCircuit, CheckCircle2, Radar, ShieldAlert } from "lucide-react";
import type { ProjectBlueprint } from "../../types/blueprint.types";

export function GenerationTraceCard({ blueprint, source }: { blueprint: ProjectBlueprint; source?: string }) {
  const trace = blueprint.trace;
  if (!trace) return null;
  const requirements = Object.entries(trace.requirements).filter(([, value]) => value !== "not detected" && value !== "not required for the first release" && value !== "none specified");
  return <section className="glass-panel blueprint-corners p-5 mb-8"><div className="flex items-start justify-between gap-4 flex-wrap mb-5"><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-xl bg-signal-500/15 flex items-center justify-center"><BrainCircuit size={18} className="text-signal-400" /></div><div><p className="font-mono text-[11px] text-line-400">GENERATION TRACE</p><h2 className="font-[family-name:var(--font-display)] text-lg font-semibold">Why this blueprint looks like this</h2></div></div><span className="font-mono text-xs rounded-full border border-line-500/30 bg-line-500/10 text-line-300 px-3 py-1">{source?.toUpperCase() ?? "DOMAIN ENGINE"} · {trace.domain.label}</span></div><div className="grid md:grid-cols-3 gap-4 mb-5"><div className="rounded-xl bg-white/[0.03] border border-white/5 p-4"><div className="flex items-center gap-2 text-paper-400 text-xs font-mono mb-2"><Radar size={14} className="text-signal-400" /> CORE ENTITY</div><p className="text-paper-100 font-medium">{trace.domain.entity}</p><p className="text-xs text-paper-500 mt-1">{trace.domain.verbs.join(" · ")}</p></div><div className="rounded-xl bg-white/[0.03] border border-white/5 p-4"><p className="text-paper-400 text-xs font-mono mb-2">DOMAIN TABLES</p><p className="text-paper-100 font-medium">{trace.domain.tables.join(", ")}</p><p className="text-xs text-paper-500 mt-1">The nouns shape the data model.</p></div><div className="rounded-xl bg-white/[0.03] border border-white/5 p-4"><p className="text-paper-400 text-xs font-mono mb-2">DOMAIN SIGNALS</p><p className="text-paper-100 font-medium">{trace.domain.stack.join(" · ")}</p><p className="text-xs text-paper-500 mt-1">Operational constraints applied.</p></div></div>{requirements.length > 0 && <div className="mb-5"><p className="text-xs font-mono text-paper-500 mb-2">EXTRACTED REQUIREMENTS</p><div className="flex flex-wrap gap-2">{requirements.map(([key, value]) => <span key={key} className="text-xs rounded-full border border-white/10 bg-white/[0.03] text-paper-300 px-3 py-1"><strong className="text-paper-100">{key}:</strong> {Array.isArray(value) ? value.join(", ") : String(value)}</span>)}</div></div>}<div className="grid md:grid-cols-3 gap-3">{trace.knowledge.map(note => <div key={note.title} className="text-xs text-paper-400"><p className="text-paper-200 font-medium mb-1">{note.title}</p><p>{note.content}</p></div>)}</div>{trace.warnings.length > 0 ? <div className="mt-5 flex items-start gap-2 text-xs text-amber-300"><ShieldAlert size={15} className="shrink-0" /><span>{trace.warnings.join(" ")}</span></div> : <div className="mt-5 flex items-center gap-2 text-xs text-emerald-300"><CheckCircle2 size={15} /> Blueprint consistency checks passed.</div>}</section>;
}
