import type { ProjectBlueprint } from "../../../src/types/blueprint.types.ts";
import type { DomainProfile } from "./domainKnowledge.ts";

function title(value: string) { return value.split(/\s+/).filter(Boolean).slice(0, 3).map(word => word[0].toUpperCase() + word.slice(1).toLowerCase()).join(""); }
function ideaNoun(idea: string) { const ignored = new Set(["a", "an", "the", "for", "with", "and", "app", "platform", "system", "tool"]); return idea.toLowerCase().replace(/[^a-z0-9\s]/g, " ").split(/\s+/).filter(word => word.length > 3 && !ignored.has(word)).slice(0, 2).map(title).join("") || "Workspace"; }

export function personalizeDemo(base: ProjectBlueprint, idea: string, domain: DomainProfile): ProjectBlueprint {
  const concept = ideaNoun(idea);
  const name = `${concept} ${title(domain.entity)}`;
  const domainTables = domain.tables.map((table, index) => ({ tableName: table, fields: [{ name: "id", type: "UUID", constraints: "PRIMARY KEY" }, { name: `${domain.entity.replace(/\s+/g, "_")}_status`, type: "VARCHAR(32)", constraints: "NOT NULL" }, { name: "created_at", type: "TIMESTAMPTZ", constraints: "DEFAULT NOW()" }], relations: [`belongs to workspace`, `supports ${domain.verbs[index % domain.verbs.length]} decisions`] }));
  const architecture = domain.architecture.map((name, index) => ({ name, description: `${name} is tailored to ${concept}, with explicit ownership, validation, retries, and auditability for ${domain.verbs[index % domain.verbs.length]} workflows.`, components: [domain.tables[index % domain.tables.length], domain.routes[index % domain.routes.length], domain.integrations[index % domain.integrations.length]] }));
  const apiDesign = domain.routes.map((route, index) => ({ method: (index === 0 ? "GET" : index === 1 ? "POST" : "PATCH") as "GET" | "POST" | "PATCH", path: `/api/${route}`, description: `${domain.verbs[index % domain.verbs.length]} ${domain.entity} records for ${concept}.`, requestBody: index === 0 ? undefined : `{ ${domain.entity.replace(/\s+/g, "_")}: string, status?: string }`, responseBody: `{ data: [], nextCursor?: string }`, authRequired: true }));
  const techStack = base.techStack.map(item => item.category === "Backend" ? { ...item, choice: domain.key === "logistics" ? "Node.js, Express, PostGIS events" : domain.key === "finance" ? "Node.js, Express, idempotent command handlers" : item.choice, reason: `Chosen for ${domain.label.toLowerCase()} workflows and ${domain.metrics[0]} instrumentation.` } : item.category === "AI" ? { ...item, reason: `Use structured generation to model ${domain.entity}, ${domain.verbs.join(", ")}, and ${domain.integrations[0]}.` } : item);
  const tasks = base.tasks.map((task, index) => ({ ...task, id: `${domain.key.slice(0, 3).toUpperCase()}-${101 + index}`, title: `${domain.verbs[index % domain.verbs.length]} ${domain.entity} using ${domain.tables[index % domain.tables.length]}`, phase: index < 3 ? "Domain foundation" : index < 6 ? "Core workflow" : "Launch hardening" }));
  return { ...base, projectName: name, summary: `${name} is a ${domain.label.toLowerCase()} product shaped around ${domain.metrics[0]}, ${domain.metrics[1]}, and ${domain.metrics[2]}. The plan is derived from the idea: “${idea}”.`, techStack, architecture, apiDesign, databaseSchema: domainTables, tasks, folderStructure: `/${concept.toLowerCase()}\n  /src\n    /features/${domain.key}\n    /workflows\n    /integrations\n  /server\n    /routes/${domain.key}\n    /services\n    /jobs\n  /prisma\n    schema.prisma`, roadmap: [{ phase: "Domain foundation", duration: "Week 1", goals: [`Model ${domain.tables.slice(0, 2).join(" and ")}`, `Define ${domain.entity} state transitions`, "Set up workspace authorization"] }, { phase: "Core workflow", duration: "Weeks 2-3", goals: domain.verbs.map(verb => `Implement ${verb} flow`) }, { phase: "Integrations and controls", duration: "Week 4", goals: domain.integrations.concat(domain.stack) }, { phase: "Launch hardening", duration: "Week 5", goals: domain.metrics.map(metric => `Instrument ${metric}`) }], futureScope: [{ title: `Advanced ${domain.entity} intelligence`, description: `Use historical ${domain.tables[0]} and ${domain.metrics[0]} to recommend the next action.`, impact: "High" }, { title: "Workflow automation", description: `Automate safe ${domain.verbs[0]} and ${domain.verbs[1]} transitions with human approval gates.`, impact: "Medium" }, ...base.futureScope.slice(2)], readme: base.readme.replace(/# .*\n/, `# ${name}\n`).replace(/resources/g, domain.tables[0]) };
}

export function validateBlueprint(blueprint: ProjectBlueprint): string[] { const warnings: string[] = []; const names = new Set(blueprint.databaseSchema.map(table => table.tableName)); for (const table of blueprint.databaseSchema) for (const relation of table.relations) { const match = relation.match(/(?:->|to)\s+([a-z_]+)/i); if (match && !["the", "a", "an", "workspace"].includes(match[1]) && !names.has(match[1])) warnings.push(`Relation in ${table.tableName} references unknown table ${match[1]}.`); } return warnings; }
