export type DomainProfile = { key: string; label: string; entity: string; verbs: string[]; tables: string[]; routes: string[]; stack: string[]; architecture: string[]; integrations: string[]; metrics: string[] };

const profiles: Record<string, DomainProfile> = {
  healthcare: { key: "healthcare", label: "Healthcare operations", entity: "care episode", verbs: ["triage", "schedule", "coordinate", "follow up"], tables: ["patients", "appointments", "care_notes", "providers"], routes: ["appointments", "care-plans", "check-ins", "providers"], stack: ["FHIR-aligned identifiers", "RBAC", "audit logging"], architecture: ["Patient identity and consent boundary", "Scheduling and care coordination workflow", "Clinical notes with immutable audit trail"], integrations: ["EHR/FHIR adapter", "SMS reminder provider", "Identity verification"], metrics: ["no-show rate", "time to follow-up", "care-plan completion"] },
  logistics: { key: "logistics", label: "Logistics and field operations", entity: "delivery run", verbs: ["dispatch", "reroute", "reconcile", "monitor"], tables: ["routes", "stops", "scans", "exceptions"], routes: ["routes", "stops", "scan-events", "exceptions"], stack: ["geospatial indexing", "event timeline", "offline-first sync"], architecture: ["Dispatch command center", "Driver mobile sync boundary", "Event-sourced route state"], integrations: ["Maps/geocoding API", "Barcode scanner", "Fleet telematics"], metrics: ["on-time delivery", "route variance", "exception resolution time"] },
  finance: { key: "finance", label: "Financial operations", entity: "financial case", verbs: ["reconcile", "approve", "forecast", "audit"], tables: ["accounts", "transactions", "rules", "review_events"], routes: ["accounts", "transactions", "reconciliation-runs", "review-cases"], stack: ["idempotency keys", "double-entry ledger", "immutable audit events"], architecture: ["Ledger and posting boundary", "Reconciliation rules engine", "Approval and compliance workflow"], integrations: ["Bank aggregation API", "Payment processor", "KYC/AML provider"], metrics: ["reconciliation accuracy", "exception aging", "cash forecast variance"] },
  education: { key: "education", label: "Learning and education", entity: "learning pathway", verbs: ["enroll", "practice", "assess", "coach"], tables: ["learners", "lessons", "attempts", "coach_notes"], routes: ["learners", "lessons", "assessments", "progress"], stack: ["progress events", "content versioning", "privacy controls"], architecture: ["Learner experience and content delivery", "Assessment and mastery engine", "Coach intervention workspace"], integrations: ["LMS/LTI connector", "Video classroom", "Email/push notifications"], metrics: ["lesson completion", "mastery progression", "intervention success"] },
  community: { key: "community", label: "Community and collaboration", entity: "member circle", verbs: ["join", "contribute", "moderate", "surface"], tables: ["members", "posts", "reactions", "moderation_cases"], routes: ["members", "posts", "moderation-cases", "notifications"], stack: ["trust signals", "moderation queue", "notification fanout"], architecture: ["Member identity and graph", "Content and conversation stream", "Trust, safety, and moderation"], integrations: ["Email/push provider", "Content moderation API", "Search/indexing service"], metrics: ["weekly active members", "healthy contribution rate", "moderation response time"] },
  commerce: { key: "commerce", label: "Commerce and marketplace", entity: "purchase journey", verbs: ["discover", "reserve", "fulfill", "measure"], tables: ["catalog_items", "carts", "orders", "fulfillment_events"], routes: ["catalog", "carts", "orders", "fulfillment"], stack: ["inventory reservations", "payment webhooks", "fulfillment state machine"], architecture: ["Searchable catalog and pricing", "Cart, checkout, and payment boundary", "Order fulfillment state machine"], integrations: ["Payment processor", "Tax/shipping API", "Email delivery provider"], metrics: ["conversion rate", "cart abandonment", "fulfillment lead time"] },
};

const keywords: Record<string, string[]> = { healthcare: ["health", "clinic", "patient", "doctor", "medical", "care"], logistics: ["delivery", "fleet", "dispatch", "warehouse", "route", "logistics", "shipment"], finance: ["finance", "bank", "invoice", "payment", "budget", "accounting", "ledger"], education: ["student", "school", "course", "learning", "teacher", "lesson", "training"], community: ["community", "social", "members", "forum", "creator", "discussion"], commerce: ["shop", "store", "marketplace", "cart", "inventory", "order", "subscription"] };

export function detectDomain(idea: string): DomainProfile { const text = idea.toLowerCase(); const scored = Object.entries(keywords).map(([key, words]) => [key, words.reduce((score, word) => score + (text.includes(word) ? 1 : 0), 0)] as const).sort((a, b) => b[1] - a[1]); return profiles[scored[0]?.[1] > 0 ? scored[0][0] : "community"]; }

export function extractRequirements(idea: string, domain: DomainProfile) { const text = idea.toLowerCase(); const includes = (...terms: string[]) => terms.some(term => text.includes(term)); return { domain: domain.label, actors: Array.from(new Set([includes("admin", "owner", "manager") ? "administrator" : "operator", includes("team", "staff", "agent") ? "team member" : "end user", includes("vendor", "provider", "teacher", "doctor") ? domain.entity + " specialist" : ""])).filter(Boolean), features: Array.from(new Set(domain.verbs.concat(includes("notification", "reminder", "alert") ? ["notifications"] : [], includes("report", "analytics", "dashboard") ? ["reporting"] : [], includes("search", "discover", "filter") ? ["search"] : [], includes("upload", "document", "file") ? ["document handling"] : [], includes("mobile", "offline") ? ["mobile/offline experience"] : []))), realtime: includes("live", "real-time", "realtime") ? "yes" : "not required for the first release", payments: includes("payment", "billing", "checkout", "subscription") ? "detected" : "not detected", integrations: includes("api", "integrat", "stripe", "map", "ehr", "lms") ? domain.integrations : ["none specified"], constraints: Array.from(new Set([includes("privacy", "sensitive", "medical") ? "sensitive data handling" : "", includes("global", "international", "multiple countries") ? "multi-region and localization" : "", includes("offline", "poor connection") ? "offline conflict resolution" : ""])).filter(Boolean) }; }

export function retrieveKnowledge(domain: DomainProfile) { return [{ title: `${domain.label} operating model`, content: `Model ${domain.entity} transitions explicitly and keep a human-readable activity timeline for ${domain.verbs[0]} and ${domain.verbs[1]} decisions.`, source: "TaskFlow domain playbook" }, { title: "Trust boundary", content: `Use workspace-scoped roles, idempotent mutations, and an audit trail around ${domain.tables[0]} and ${domain.tables[1]}.`, source: "TaskFlow engineering notes" }, { title: "Measurable product loop", content: `Instrument ${domain.metrics.join(", ")} and define empty, failure, retry, and escalation states for the first release.`, source: "TaskFlow delivery notes" }]; }
